# DataFrame - Amazon Sample

Este DataFrame se obtiene a partir del archivo JSON generado desde una muestra del dataset original de ventas de Amazon. Se utilizará para explorar la estructura de los datos y realizar análisis descriptivos básicos.

## Cargar la data desde el JSON

In [26]:
import pandas as pd

df_json = pd.read_json("data/amazon_sample.json")
print("Dimensiones:", df_json.shape)

Dimensiones: (5000, 24)

## 2: Explorar estructura

### Exploración de los datos

Se verifica la estructura general del DataFrame para conocer la cantidad de registros y atributos disponibles.

In [27]:
df_json.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               5000 non-null   int64
 1   Order ID            5000 non-null   str
 2   Date                5000 non-null   datetime64[us]
 3   Status              5000 non-null   str
 4   Fulfilment          5000 non-null   str
 5   Sales Channel       5000 non-null   str
 6   ship-service-level  5000 non-null   str
 7   Style               5000 non-null   str
 8   SKU                 5000 non-null   str
 9   Category            5000 non-null   str
 10  Size                5000 non-null   str
 11  ASIN                5000 non-null   str
 12  Courier Status      4724 non-null   str
 13  Qty                 5000 non-null   int64
 14  currency            4662 non-null   str
 15  Amount              4662 non-null   float64
 16  ship-city           4998 non-null   str
 17  ship-state          4998 non-null   str
 18  ship-postal-code    4998 non-null   float64
 19  ship-country        4998 non-null   str
 20  promotion-ids       3228 non-null   str
 21  B2B                 5000 non-null   bool
 22  fulfilled-by        1539 non-null   str
 23  Unnamed: 22         0 non-null      float64
dtypes: bool(1), datetime64[us](1), float64(3), int64(2), str(17)
memory usage: 903.4 KB

## 3: Mostrar primeras 5 filas

### Primeras 5 filas

Se visualizan los primeros registros para comprender la distribución y contenido de los datos.

In [28]:
df_json.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

## 4: Identificar columnas con valores nulos

### Identificación de valores nulos

Se identifican las columnas que contienen valores faltantes.

In [29]:
columnas_nulas = df_json.columns[df_json.isnull().any()]

print("Columnas con valores nulos:")
print(columnas_nulas)

Columnas con valores nulos:
Index(['Courier Status', 'currency', 'Amount', 'ship-city', 'ship-state',
       'ship-postal-code', 'ship-country', 'promotion-ids', 'fulfilled-by',
       'Unnamed: 22'],
      dtype='str')

## 5: Contar valores faltantes en cada columna

### Conteo de valores faltantes

Se contabilizan los valores faltantes presentes en cada columna.

In [30]:
df_json.isnull().sum()

index                    0
Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       0
Style                    0
SKU                      0
Category                 0
Size                     0
ASIN                     0
Courier Status         276
Qty                      0
currency               338
Amount                 338
ship-city                2
ship-state               2
ship-postal-code         2
ship-country             2
promotion-ids         1772
B2B                      0
fulfilled-by          3461
Unnamed: 22           5000
dtype: int64

### 6. Promedio, máximo y mínimo

In [31]:
df_json.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Unnamed: 22']

In [32]:
df_json["Amount"] = pd.to_numeric(
    df_json["Amount"],
    errors="coerce"
)

print("Promedio:", df_json["Amount"].mean())
print("Máximo:", df_json["Amount"].max())
print("Mínimo:", df_json["Amount"].min())

Promedio: 622.2098455598456
Máximo: 2224.0
Mínimo: 0.0

### 7. Máximo y mínimo agrupado

## Agrupación de datos

Se obtiene el valor máximo y mínimo de ventas agrupado por categoría y estado del pedido.

In [33]:
df_json.groupby(
    ["Category", "Status"]
)["Amount"].agg(
    ["max", "min"]
)

                                                max     min
Category      Status
Blouse        Cancelled                      665.00  313.33
              Shipped                        665.00    0.00
              Shipped - Delivered to Buyer   665.00    0.00
              Shipped - Returned to Seller   625.00  518.00
Bottom        Cancelled                      493.34  493.34
              Shipped                        518.00    0.00
              Shipped - Delivered to Buyer   518.00  284.00
Ethnic Dress  Shipped                        899.00    0.00
              Shipped - Delivered to Buyer   999.00  637.00
              Shipped - Returned to Seller   899.00  899.00
Saree         Shipped                        989.00  620.00
Set           Cancelled                     1902.86  449.00
              Shipped                       2224.00    0.00
              Shipped - Delivered to Buyer  1695.00    0.00
              Shipped - Lost in Transit        0.00    0.00
              Shipped - Rejected by Buyer    654.00  654.00
              Shipped - Returned to Seller  1399.00    0.00
Top           Cancelled                      690.00  329.00
              Shipped                        864.00    0.00
              Shipped - Delivered to Buyer  1099.00    0.00
              Shipped - Returned to Seller   599.00    0.00
Western Dress Cancelled                      899.00  393.33
              Shipped                       1499.00    0.00
              Shipped - Delivered to Buyer  2175.00    0.00
              Shipped - Lost in Transit        0.00    0.00
              Shipped - Returned to Seller   791.00    0.00
kurta         Cancelled                      884.76  246.67
              Shipped                       1099.00    0.00
              Shipped - Delivered to Buyer  1249.00    0.00
              Shipped - Rejected by Buyer    568.00  568.00
              Shipped - Returned to Seller  1128.00    0.00